# Generated by Django 5.2.4 on 2025-07-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/sweets')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='all', max_length=50)),
                ('ratings', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('feature', models.BooleanField(default=False)),
            ],
        ),
    ]
